from django.core.exceptions import ValidationError
from ..models import Inventory, InventoryHistory


class InventoryService:
    pass
